### PR TITLE
added time.html to javascript folder

### PR DESCRIPTION
**Pull request by ibimina**
Added time javascript project

### CODE REVIEW

**Comment by ibimina** [comment]
@sanskarmalkhede kindly review.
Thanks

**Comment by sanskarmalkhede** [comment]
I have reviewed your code. Thank you for your contribution.
Before accepting PR I would like ask did starred the repo ?

**Comment by ibimina** [comment]
@sanskarmalkhede yes I did

**Comment by sanskarmalkhede** [comment]
Thank you for your contribution, you PR has been merged✌🏻

**Pull request merged**
