### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SurbhiSharma15**
Kadane's algorithm in optimised O(n) complexity.

### CODE REVIEW

**Comment by sanskarmalkhede** [comment]
I had to delete your one code file because it was outside of directory. But before accepting your PR, did you starred this repo?

**Comment by SurbhiSharma15** [comment]
Yes I have starred this repo....and I made three pull requests inside the
repository basic-programs/c++ folder....
Please accept my codes :)

**Comment by sanskarmalkhede** [comment]
Thank you for your contribution, your PR has been merged.
Keep contributing✌🏻

**Comment by SurbhiSharma15** [comment]
Thanks for merging!!! I actually created three files in your repository..so
can you please tell me will those three codes count as three different
contributions or just one?

**Comment by sanskarmalkhede** [comment]
There were three files but all of them were committed in one PR, so it will be counted as one. You can check the same on your Hacktoberfest profile page.

**Comment by SurbhiSharma15** [comment]
Ok, thanks for the clarification. created a new PR :)

**Pull request merged**
