### PR TITLE
Update readme.md (Add content and Fix Grammar errors)

### PR DESCRIPTION
**Pull request by SSHSRN**

### CODE REVIEW

**Comment by SSHSRN** [comment]
@sanskarmalkhede Kindly check!

**Comment by sanskarmalkhede** [comment]
Can you add this same below "What is Hacktoberfest?", then I merge your PR.
Before everything make sure that you have starred the repo⭐

**Comment by SSHSRN** [comment]
I have updated it now! @sanskarmalkhede Kindly check.

**Comment by sanskarmalkhede** [comment]
Everything fine now except you starring this repo, do it first.

**Comment by SSHSRN** [comment]
> Everything fine now except you starring this repo, do it first.

image
done it yesterday itself, bro.

**Comment by sanskarmalkhede** [comment]
Thank for your contribution.

**Pull request merged**
