### PR TITLE
Create Java_bfs.java

### PR DESCRIPTION
**Pull request by A-Prvz**
I want to illustrate bfs transversal in java.

### CODE REVIEW

**Comment by sanskarmalkhede** [comment]
Thank you! Your PR has been merged ✌🏻
Make sure that you have starred the repository⭐

**Comment by A-Prvz** [comment]
Hello, I did not get why this was labelled invalid?

**Comment by sanskarmalkhede** [comment]
you directly committed to root directory. You need to upload you java code file in java folder.

**Comment by A-Prvz** [comment]
Ok, I think I've it correct this time :).

**Pull request merged**
