### PR TITLE
Adddist

### PR DESCRIPTION
**Pull request by Sayan115**

### CODE REVIEW

**Comment by sanskarmalkhede** [comment]
Please star the repo first ⭐

**Comment by Sayan115** [comment]
Already done.

**Comment by sanskarmalkhede** [comment]
Thank you, your PR has been merged.
Keep contributing✌️

**Comment by Sayan115** [comment]
My PR has been excluded from Hacktoberfest

**Comment by sanskarmalkhede** [comment]
I have no idea. I have accepted your PR and also labelled it as "hacktoberfest-accepted"

**Pull request merged**
