### PR TITLE
Create Circular_Linked_List.c

### PR DESCRIPTION
**Pull request by Badal-05**
Provided menu-driven C - code for implementation of Circular Linked List.

### CODE REVIEW

**Comment by sanskarmalkhede** [comment]
Unfortunately I can cannot accept your PR because you have not uploaded your C code file in the specific folder. Please create another PR properly. But before everything make sure that you have starred the repository.

**Comment by Badal-05** [comment]
Okay 👍

**Comment by Badal-05** [comment]
I have edited could you check it once.

**Comment by sanskarmalkhede** [comment]
the directory of your code is showing same to  me. what have you changed?

**Comment by Badal-05** [comment]
Sorry to bother you again but I am a newbie. I created a fork of your repo.
Then it showed Badal-05/basic programs.
There I went to C folder and created two files for circular and doubly
linked list.

Could you guide me where I am wrong.

**Comment by Badal-05** [comment]
Do I need to fork or I should directly add the code in your repository's c
folder ?

**Comment by sanskarmalkhede** [comment]
actually you committed to root directory of the repo. You need to go inside C folder and then upload your code file.
for eg. C/Circular_Linked_List.c

**Comment by Badal-05** [comment]
Okay thanks for the help and kind acceptance.😊

**Pull request closed without merging**
